name: Setup
description: "Setups the Elixir environment"

runs:
  using: "composite"
  steps:
      - name: Install system dependencies
        shell: bash
        run: sudo apt-get install -y libsodium-dev