name: Setup
description: "Setups the Elixir environment"

inputs:
  fail-on-failure:
        description: 'Should fail on dependency restoration'
        required: false
        default: false

runs:
  using: "composite"
  steps:
      - name: Install system dependencies
        shell: bash
        run: sudo apt-get install -y libsodium-dev

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1.16.0
        with:
          elixir-version: '1.15.6'
          otp-version: '26.1.2'

      - name: Restore dependencies cache
        id: deps-cache
        uses: actions/cache@v3.3.2
        with:
          path: deps
          key: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-

      - name: Fail on dependencies cache miss
        shell: bash
        if: ${{ (inputs.fail-on-failure == 'true') && steps.deps-cache.outputs.cache-hit != 'true' }}
        run: /bin/false

      - name: Fetch dependencies
        shell: bash
        run: mix deps.get

      - name: Build dependencies
        shell: bash
        run: mix deps.compile

      - name: Restore PLT cache
        id: plt-cache
        uses: actions/cache@v3.3.2
        with:
          path: plts
          key: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-

      - name: Fail on PLT cache miss
        shell: bash
        if: ${{ (inputs.fail-on-failure == 'true') && steps.plt-cache.outputs.cache-hit != 'true' }}
        run: /bin/false