name: Construct caches and run checks on base

on:
  push:
    branches: [ "base" ]

permissions:
  contents: read

jobs:
  construct-caches:
    name: Construct caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup

      - name: Create PLTs
        run: mix dialyzer --plt

  run-checks:
    name: Run checks
    needs: construct-caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: true

      - uses: ./.github/workflows/checks

      - uses: ./.github/workflows/format
        if: ${{ !cancelled() }}

  build-docs:
    name: build docs
    needs: construct-caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: true

      - uses: ./.github/workflows/docs
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
