name: Construct caches and run checks on base

on:
  push:
    branches: [ "base" ]

permissions:
  contents: read

jobs:
  construct-caches:
    name: Construct caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup

      - name: Create PLTs
        run: mix dialyzer --plt

  run-checks:
    name: Run checks
    needs: construct-caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: true

      - uses: ./.github/workflows/checks

      - uses: ./.github/workflows/format
        if: ${{ !cancelled() }}

  build-docs:
    name: build docs
    needs: construct-caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup
        with:
          fail-on-failure: true


      - name: Build docs
        run: mix docs
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          keep_files: true
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doc
          publish_branch: gh-pages
