name: Run checks on main or next

on:
  push:
    branches: [ "main", "next" ]

permissions:
  contents: read

jobs:
  all:
    name: Tests, dialyzer, format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - uses: ./.github/workflows/setup

      - uses: ./.github/workflows/checks

      - uses: ./.github/workflows/format
        if: ${{ !cancelled() }}