name: Pull request checks

on:
  pull_request:
    branches: [ "base" ]

permissions:
  contents: read

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        revision: ['topic', 'next']
    name: Tests, dialyzer, format
    runs-on: ubuntu-latest
    steps:
    - name: Check out topic
      uses: actions/checkout@v4.1.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Try merge with next
      id: try_merge
      continue-on-error: true
      if: matrix.revision == 'next'
      run: >
        git checkout next &&
        git -c user.name='Anoma CI' -c user.email='nobody@localhost'
        merge -m 'Automerge with next'
        ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/workflows/setup
      if: steps.try_merge.outcome != 'failure'
      with:
        fail-on-failure: true

    - uses: ./.github/workflows/checks
      if: steps.try_merge.outcome != 'failure'


    - uses: ./.github/workflows/format
      if: ${{ !cancelled() && steps.try_merge.outcome != 'failure' }}